services:
  backend:
    image: "bankaccountcobol/backend"
    build:
      dockerfile: "backend/Dockerfile"
    container_name: "bankaccountcobol-backend"
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./app_storage
        target: /opt/app/storage

  frontend:
    image: "bankaccountcobol/frontend"
    build:
      dockerfile: "frontend/Dockerfile"
    container_name: "bankaccountcobol-frontend"
    ports:
      - "80:80"
    depends_on:
      - backend